# Generated by Django 5.2.7 on 2025-11-04 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_cartmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='quality',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
