# Generated by Django 5.2.7 on 2025-11-05 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_cartmodel_quality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartmodel',
            old_name='quality',
            new_name='quantity',
        ),
    ]
